### ISSUE TITLE
Set ist keine Modellkategorie mit Bijektionen, Injektionen und Surjektionen

### ISSUE THREAD

**Issue by timjb** [iblech/modellkategorien#1]
Man kann nicht jede Abbildung als Komposition einer Injektion gefolgt von einer Bijektion und auch nicht jede Abbildung als Komposition einer Bijektion und einer Surjektion schreiben.

**Comment by timjb** [comment]
Fun Fact: Es gibt [genau neun](http://www.math.harvard.edu/~oantolin/notes/modelcatsets.html) Modellkategoriestrukturen auf Set (aber die behauptete vom Übungsblatt ist nicht darunter)

**Comment by timjb** [comment]
Außerdem muss ein Morphismus, der die LHHE bzgl. aller Surjektionen besitzt, nicht surjektiv sein (injektiv schon).

**Comment by iblech** [comment]
Danke! Eine interessante Quelle hast du da aufgetrieben!
